//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GorillaDocs.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GorillaDocs.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string _Cancel {
            get {
                return ResourceManager.GetString("_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _No.
        /// </summary>
        public static string _No {
            get {
                return ResourceManager.GetString("_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Office.
        /// </summary>
        public static string _Office {
            get {
                return ResourceManager.GetString("_Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string _OK {
            get {
                return ResourceManager.GetString("_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string _Type {
            get {
                return ResourceManager.GetString("_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Yes.
        /// </summary>
        public static string _Yes {
            get {
                return ResourceManager.GetString("_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap action_add_16xMD {
            get {
                object obj = ResourceManager.GetObject("action_add_16xMD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add the current contact information to your list of Favourite contacts.
        /// </summary>
        public static string AddFavouriteTooltip {
            get {
                return ResourceManager.GetString("AddFavouriteTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Table.
        /// </summary>
        public static string AddTableView_Caption {
            get {
                return ResourceManager.GetString("AddTableView_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of _columns:.
        /// </summary>
        public static string AddTableView_NumberOfColumns {
            get {
                return ResourceManager.GetString("AddTableView_NumberOfColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of _rows:.
        /// </summary>
        public static string AddTableView_NumberOfRows {
            get {
                return ResourceManager.GetString("AddTableView_NumberOfRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table _heading:.
        /// </summary>
        public static string AddTableView_TableHeading {
            get {
                return ResourceManager.GetString("AddTableView_TableHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table _source:.
        /// </summary>
        public static string AddTableView_TableSource {
            get {
                return ResourceManager.GetString("AddTableView_TableSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap arrow_back_16xLG {
            get {
                object obj = ResourceManager.GetObject("arrow_back_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap arrow_Forward_16xLG {
            get {
                object obj = ResourceManager.GetObject("arrow_Forward_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap arrow_Previous_16xLG_color {
            get {
                object obj = ResourceManager.GetObject("arrow_Previous_16xLG_color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap B1 {
            get {
                object obj = ResourceManager.GetObject("B1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap B2 {
            get {
                object obj = ResourceManager.GetObject("B2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap B3 {
            get {
                object obj = ResourceManager.GetObject("B3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BT {
            get {
                object obj = ResourceManager.GetObject("BT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BTI {
            get {
                object obj = ResourceManager.GetObject("BTI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Address:.
        /// </summary>
        public static string ContactAddress {
            get {
                return ResourceManager.GetString("ContactAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Company:.
        /// </summary>
        public static string ContactCompany {
            get {
                return ResourceManager.GetString("ContactCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delivery:.
        /// </summary>
        public static string ContactDelivery {
            get {
                return ResourceManager.GetString("ContactDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Department:.
        /// </summary>
        public static string ContactDepartment {
            get {
                return ResourceManager.GetString("ContactDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Email:.
        /// </summary>
        public static string ContactEmail {
            get {
                return ResourceManager.GetString("ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Fax:.
        /// </summary>
        public static string ContactFax {
            get {
                return ResourceManager.GetString("ContactFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Name:.
        /// </summary>
        public static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Salutation:.
        /// </summary>
        public static string ContactSalutation {
            get {
                return ResourceManager.GetString("ContactSalutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Title:.
        /// </summary>
        public static string ContactTitle {
            get {
                return ResourceManager.GetString("ContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC.
        /// </summary>
        public static string ContentControl_CC {
            get {
                return ResourceManager.GetString("ContentControl_CC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        public static string ContentControl_DeliveryEnding {
            get {
                return ResourceManager.GetString("ContentControl_DeliveryEnding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient.
        /// </summary>
        public static string ContentControl_Recipient {
            get {
                return ResourceManager.GetString("ContentControl_Recipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap D {
            get {
                object obj = ResourceManager.GetObject("D", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap D1 {
            get {
                object obj = ResourceManager.GetObject("D1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap D11 {
            get {
                object obj = ResourceManager.GetObject("D11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap D2 {
            get {
                object obj = ResourceManager.GetObject("D2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap D3 {
            get {
                object obj = ResourceManager.GetObject("D3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.
        /// </summary>
        public static string Delivery_Email {
            get {
                return ResourceManager.GetString("Delivery_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to facsimile.
        /// </summary>
        public static string Delivery_Facsimile {
            get {
                return ResourceManager.GetString("Delivery_Facsimile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other.
        /// </summary>
        public static string Delivery_Other {
            get {
                return ResourceManager.GetString("Delivery_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DiscardChanges {
            get {
                object obj = ResourceManager.GetObject("DiscardChanges", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DP {
            get {
                object obj = ResourceManager.GetObject("DP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap EditDocument {
            get {
                object obj = ResourceManager.GetObject("EditDocument", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Office.
        /// </summary>
        public static string frmChangeOffice_Caption {
            get {
                return ResourceManager.GetString("frmChangeOffice_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string frmNewDocument_All {
            get {
                return ResourceManager.GetString("frmNewDocument_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _All Templates.
        /// </summary>
        public static string frmNewDocument_AllTemplates {
            get {
                return ResourceManager.GetString("frmNewDocument_AllTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Template.
        /// </summary>
        public static string frmNewDocument_Caption {
            get {
                return ResourceManager.GetString("frmNewDocument_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Categories.
        /// </summary>
        public static string frmNewDocument_Categories {
            get {
                return ResourceManager.GetString("frmNewDocument_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Document Type.
        /// </summary>
        public static string frmNewDocument_DocumentType {
            get {
                return ResourceManager.GetString("frmNewDocument_DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My _Recent.
        /// </summary>
        public static string frmNewDocument_MyRecent {
            get {
                return ResourceManager.GetString("frmNewDocument_MyRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GorillaDocs {
            get {
                object obj = ResourceManager.GetObject("GorillaDocs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GorillaDocs_sml {
            get {
                object obj = ResourceManager.GetObject("GorillaDocs_sml", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap H1 {
            get {
                object obj = ResourceManager.GetObject("H1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap H2 {
            get {
                object obj = ResourceManager.GetObject("H2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap H3 {
            get {
                object obj = ResourceManager.GetObject("H3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap H4 {
            get {
                object obj = ResourceManager.GetObject("H4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap H5 {
            get {
                object obj = ResourceManager.GetObject("H5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap H6 {
            get {
                object obj = ResourceManager.GetObject("H6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ImportOrLoad_8600 {
            get {
                object obj = ResourceManager.GetObject("ImportOrLoad_8600", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IN {
            get {
                object obj = ResourceManager.GetObject("IN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ItalicD {
            get {
                object obj = ResourceManager.GetObject("ItalicD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap L1 {
            get {
                object obj = ResourceManager.GetObject("L1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap L2 {
            get {
                object obj = ResourceManager.GetObject("L2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap L3 {
            get {
                object obj = ResourceManager.GetObject("L3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap L4 {
            get {
                object obj = ResourceManager.GetObject("L4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Landscape {
            get {
                object obj = ResourceManager.GetObject("Landscape", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Attention:.
        /// </summary>
        public static string LetterDetailsView_Attention {
            get {
                return ResourceManager.GetString("LetterDetailsView_Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter.
        /// </summary>
        public static string LetterDetailsView_Caption {
            get {
                return ResourceManager.GetString("LetterDetailsView_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter.
        /// </summary>
        public static string LetterDetailsView_Caption1 {
            get {
                return ResourceManager.GetString("LetterDetailsView_Caption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _CC.
        /// </summary>
        public static string LetterDetailsView_CC {
            get {
                return ResourceManager.GetString("LetterDetailsView_CC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Date:.
        /// </summary>
        public static string LetterDetailsView_Date {
            get {
                return ResourceManager.GetString("LetterDetailsView_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Enclosure.
        /// </summary>
        public static string LetterDetailsView_Enclosure {
            get {
                return ResourceManager.GetString("LetterDetailsView_Enclosure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Legal notice:.
        /// </summary>
        public static string LetterDetailsView_LegalNotice {
            get {
                return ResourceManager.GetString("LetterDetailsView_LegalNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Legal notice:.
        /// </summary>
        public static string LetterDetailsView_LegalNotices {
            get {
                return ResourceManager.GetString("LetterDetailsView_LegalNotices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Other contact.
        /// </summary>
        public static string LetterDetailsView_OtherContact {
            get {
                return ResourceManager.GetString("LetterDetailsView_OtherContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Email address:.
        /// </summary>
        public static string LetterDetailsView_OtherContactEmail {
            get {
                return ResourceManager.GetString("LetterDetailsView_OtherContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Name:.
        /// </summary>
        public static string LetterDetailsView_OtherContactName {
            get {
                return ResourceManager.GetString("LetterDetailsView_OtherContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Direct number:.
        /// </summary>
        public static string LetterDetailsView_OtherContactPhone {
            get {
                return ResourceManager.GetString("LetterDetailsView_OtherContactPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Title:.
        /// </summary>
        public static string LetterDetailsView_OtherContactTitle {
            get {
                return ResourceManager.GetString("LetterDetailsView_OtherContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Our ref:.
        /// </summary>
        public static string LetterDetailsView_OurRef {
            get {
                return ResourceManager.GetString("LetterDetailsView_OurRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient.
        /// </summary>
        public static string LetterDetailsView_Recipient {
            get {
                return ResourceManager.GetString("LetterDetailsView_Recipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Salutation:.
        /// </summary>
        public static string LetterDetailsView_Salutation {
            get {
                return ResourceManager.GetString("LetterDetailsView_Salutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Signoff:.
        /// </summary>
        public static string LetterDetailsView_Signoff {
            get {
                return ResourceManager.GetString("LetterDetailsView_Signoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender _1.
        /// </summary>
        public static string LetterDetailsView_Signoff1 {
            get {
                return ResourceManager.GetString("LetterDetailsView_Signoff1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender _2.
        /// </summary>
        public static string LetterDetailsView_Signoff2 {
            get {
                return ResourceManager.GetString("LetterDetailsView_Signoff2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Email address:.
        /// </summary>
        public static string LetterDetailsView_Signoff2Email {
            get {
                return ResourceManager.GetString("LetterDetailsView_Signoff2Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Name:.
        /// </summary>
        public static string LetterDetailsView_Signoff2Name {
            get {
                return ResourceManager.GetString("LetterDetailsView_Signoff2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Direct number:.
        /// </summary>
        public static string LetterDetailsView_Signoff2Phone {
            get {
                return ResourceManager.GetString("LetterDetailsView_Signoff2Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Title:.
        /// </summary>
        public static string LetterDetailsView_Signoff2Title {
            get {
                return ResourceManager.GetString("LetterDetailsView_Signoff2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Subject:.
        /// </summary>
        public static string LetterDetailsView_Subject {
            get {
                return ResourceManager.GetString("LetterDetailsView_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Your ref:.
        /// </summary>
        public static string LetterDetailsView_YourRef {
            get {
                return ResourceManager.GetString("LetterDetailsView_YourRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Office1 {
            get {
                object obj = ResourceManager.GetObject("Office1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pencil_003_16xMD {
            get {
                object obj = ResourceManager.GetObject("pencil_003_16xMD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Portrait {
            get {
                object obj = ResourceManager.GetObject("Portrait", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PowerPointTemplate {
            get {
                object obj = ResourceManager.GetObject("PowerPointTemplate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the current contact information to your list of Favourite contacts.
        /// </summary>
        public static string RemoveFavouriteTooltip {
            get {
                return ResourceManager.GetString("RemoveFavouriteTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap S1 {
            get {
                object obj = ResourceManager.GetObject("S1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap S2 {
            get {
                object obj = ResourceManager.GetObject("S2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap S3 {
            get {
                object obj = ResourceManager.GetObject("S3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap S4 {
            get {
                object obj = ResourceManager.GetObject("S4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap S5 {
            get {
                object obj = ResourceManager.GetObject("S5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap S6 {
            get {
                object obj = ResourceManager.GetObject("S6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap save_16xLG {
            get {
                object obj = ResourceManager.GetObject("save_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Email address:.
        /// </summary>
        public static string SenderEmail {
            get {
                return ResourceManager.GetString("SenderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Name:.
        /// </summary>
        public static string SenderName {
            get {
                return ResourceManager.GetString("SenderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Direct number:.
        /// </summary>
        public static string SenderPhone {
            get {
                return ResourceManager.GetString("SenderPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Title:.
        /// </summary>
        public static string SenderTitle {
            get {
                return ResourceManager.GetString("SenderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SH {
            get {
                object obj = ResourceManager.GetObject("SH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SharePoint {
            get {
                object obj = ResourceManager.GetObject("SharePoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap sharepointfoundation16 {
            get {
                object obj = ResourceManager.GetObject("sharepointfoundation16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By.
        /// </summary>
        public static string Signoff_By {
            get {
                return ResourceManager.GetString("Signoff_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Signoff_Name {
            get {
                return ResourceManager.GetString("Signoff_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Signoff_Title {
            get {
                return ResourceManager.GetString("Signoff_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap StatusAnnotations_Complete_and_ok_16xLG {
            get {
                object obj = ResourceManager.GetObject("StatusAnnotations_Complete_and_ok_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Symbols_Blocked_32xLG {
            get {
                object obj = ResourceManager.GetObject("Symbols_Blocked_32xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Symbols_Complete_and_ok_16xLG {
            get {
                object obj = ResourceManager.GetObject("Symbols_Complete_and_ok_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Symbols_Critical_32xLG {
            get {
                object obj = ResourceManager.GetObject("Symbols_Critical_32xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ToggleLogo {
            get {
                object obj = ResourceManager.GetObject("ToggleLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap user_32xLG {
            get {
                object obj = ResourceManager.GetObject("user_32xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap WordTemplate {
            get {
                object obj = ResourceManager.GetObject("WordTemplate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
