//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GorillaDocs.strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GorillaDocs.strings.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved..
        /// </summary>
        public static string All_rights_reserved {
            get {
                return ResourceManager.GetString("All_rights_reserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appendix.
        /// </summary>
        public static string Appendix {
            get {
                return ResourceManager.GetString("Appendix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention:.
        /// </summary>
        public static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bcc:.
        /// </summary>
        public static string BCC {
            get {
                return ResourceManager.GetString("BCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin typing here.
        /// </summary>
        public static string Begin_typing_here {
            get {
                return ResourceManager.GetString("Begin_typing_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cc:.
        /// </summary>
        public static string CC {
            get {
                return ResourceManager.GetString("CC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clause.
        /// </summary>
        public static string Clause {
            get {
                return ResourceManager.GetString("Clause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clause Number.
        /// </summary>
        public static string ClauseNumber {
            get {
                return ResourceManager.GetString("ClauseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents.
        /// </summary>
        public static string Contents {
            get {
                return ResourceManager.GetString("Contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © {0} {1}.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dated.
        /// </summary>
        public static string Dated {
            get {
                return ResourceManager.GetString("Dated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear .
        /// </summary>
        public static string Dear {
            get {
                return ResourceManager.GetString("Dear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient.
        /// </summary>
        public static string Delivery {
            get {
                return ResourceManager.GetString("Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encl.
        /// </summary>
        public static string Encl {
            get {
                return ResourceManager.GetString("Encl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executed.
        /// </summary>
        public static string Executed {
            get {
                return ResourceManager.GetString("Executed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution.
        /// </summary>
        public static string Execution {
            get {
                return ResourceManager.GetString("Execution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executive summary.
        /// </summary>
        public static string Executive_summary {
            get {
                return ResourceManager.GetString("Executive_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facsimile Transmission.
        /// </summary>
        public static string Facsimile_transmission {
            get {
                return ResourceManager.GetString("Facsimile_transmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax:.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From:.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heading.
        /// </summary>
        public static string Heading {
            get {
                return ResourceManager.GetString("Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert appropriate execution clause for each party here.
        /// </summary>
        public static string Insert_appropriate_execution_clause_for_each_party_here {
            get {
                return ResourceManager.GetString("Insert_appropriate_execution_clause_for_each_party_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memorandum.
        /// </summary>
        public static string Memorandum {
            get {
                return ResourceManager.GetString("Memorandum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operative provisions.
        /// </summary>
        public static string Operative_provisions {
            get {
                return ResourceManager.GetString("Operative_provisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other contact:.
        /// </summary>
        public static string Other_contact {
            get {
                return ResourceManager.GetString("Other_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our ref:.
        /// </summary>
        public static string OurRef {
            get {
                return ResourceManager.GetString("OurRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages (w/cover):.
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parties.
        /// </summary>
        public static string Parties {
            get {
                return ResourceManager.GetString("Parties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re:.
        /// </summary>
        public static string Re {
            get {
                return ResourceManager.GetString("Re", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recitals.
        /// </summary>
        public static string Recitals {
            get {
                return ResourceManager.GetString("Recitals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref:.
        /// </summary>
        public static string Ref {
            get {
                return ResourceManager.GetString("Ref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table of contents.
        /// </summary>
        public static string Table_of_contents {
            get {
                return ResourceManager.GetString("Table_of_contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel:.
        /// </summary>
        public static string Tel {
            get {
                return ResourceManager.GetString("Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To:.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ref:.
        /// </summary>
        public static string YourRef {
            get {
                return ResourceManager.GetString("YourRef", resourceCulture);
            }
        }
    }
}
